### ISSUE TITLE
Add CI status ?

### ISSUE THREAD

**Issue by Carreau** [minrk/all-my-pulls#2]
Just a proposal. 

Also what about a all-my-issues :-)

**Comment by minrk** [comment]
ha, I think all-my-issues is too many. CI status should be easy enough, I've added the hacktoberfest label to invite anyone to give it a go.

**Comment by ghost** [comment]
Taking this :smile:

**Comment by ghost** [comment]
Just leaving this as a note, to make it work locally using your oauth etc.

```
git clone && cd all-my-pulls
yarn global add hostile
hostile set 127.0.0.1 local.minrk.net
python -m SimpleHTTPServer 8000
```

Then http://local.minrk.net:8000.

**Comment by Carreau** [comment]
Well that was fast ! Thanks !
